### ISSUE TITLE
Classy violates Contnent Security Policy

### ISSUE THREAD

**Issue by GodBleak** [lume/classy-solid#5]
I'm unable to use classy while using the `script-src` directive in a Content Security Policy due to the use of the `new Function()` constructor. Is it possible to avoid using it?

**Comment by trusktr** [comment]
I don't see the use of `new Function` anywhere. Is it perhaps your build tool adding that?

**Comment by trusktr** [comment]
Almost ready to release classy-solid on stage 3 decorators. I've checked locally, and there are no uses of `new Function`.

The upcoming release will no longer support legacy decorators, only the new stage 3 decorators (https://github.com/lume/classy-solid/pull/4), to keep things simple in the implementation. Then we'll also need to update Vite docs to use the latest Babel decorator config.

Closing since it won't be relevant, and maybe even the problem goes away whatever it was (I'm guessing build tool thing?).

**Comment by GodBleak** [comment]
I think it's actually the dependency `lowclass` that's causing it, these lines particularly [`lowclass/Class.ts:81`](https://github.com/trusktr/lowclass/blob/main/src/Class.ts#L81), [`lowclass/Class.ts:298`](https://github.com/trusktr/lowclass/blob/main/src/Class.ts#L298), and [`lowclass/Class.ts:540`](https://github.com/trusktr/lowclass/blob/main/src/Class.ts#L540)
